
import { AchievementItem, Tab } from './types';
import { GraduationCap, Award, FileText, Trophy, Target } from 'lucide-react';

export const tabs: Tab[] = [
  { id: 'certificates', label: 'Certificates', icon: FileText },
  { id: 'academic', label: 'Academic', icon: GraduationCap },
  { id: 'scholarships', label: 'Scholarships', icon: Award },
  { id: 'events', label: 'Events', icon: Trophy },
  { id: 'results', label: 'Results', icon: Target },
];

export const achievementsData: AchievementItem[] = [
  {
    id: 1,
    title: 'Quiz Competition on Energy Conservation',
    description: 'Certificate of participation in Quiz Competition on Energy Conservation organized by Bureau of Energy Efficiency (BEE) on MyGov',
    date: '2025',
    category: 'certificate',
    likes: 45,
    image: '/lovable-uploads/48bcc534-1b1c-4a72-a07d-b751513fa958.png',
  },
  {
    id: 2,
    title: 'World Environment Day Quiz',
    description: 'Certificate of participation for successfully completing the Quiz on "Ending Plastic Pollution" on World Environment Day 2025',
    date: '2025',
    category: 'certificate',
    likes: 38,
    image: '/lovable-uploads/447197db-cc20-4adc-a55a-c6e145b2a0a2.png',
  },
  {
    id: 3,
    title: 'Atmanirbhar Innovation in National Security',
    description: 'Certificate of participation in Quiz on Rise of Atmanirbhar Innovation in National Security by Ministry of Defence',
    date: '2025',
    category: 'certificate',
    likes: 42,
    image: '/lovable-uploads/76cb7ba4-ac27-4eb7-a747-945c8f2e9740.png',
  },
  {
    id: 4,
    title: 'Viksit Bharat 2025 Quiz',
    description: 'Certificate of participation in Viksit Bharat 2025 Quiz - acknowledging efforts towards national development',
    date: '2025',
    category: 'certificate',
    likes: 51,
    image: '/lovable-uploads/d0fe4b18-871b-4a52-b968-409898268173.png',
  },
  {
    id: 15,
    title: '9th Grade - Final Results',
    description: 'Iqra Educational Institute - Final examination results with A+ grade in all subjects including English, Math, Science, S_Science, Urdu, and Kashmiri. Overall Grade: A+',
    date: '2024-25',
    category: 'academic',
    likes: 28,
    image: '/lovable-uploads/8ae948a6-e7d5-4834-b51a-845d61c9f64b.png',
  },
  {
    id: 16,
    title: '8th Grade - Sessional Results',
    description: 'Iqra Educational Institute - Sessional 1st & 2nd examination results with A+ grades in all subjects. Total percentage: 100%',
    date: '2023-24',
    category: 'academic',
    likes: 25,
    image: '/lovable-uploads/90950a72-9fcf-4542-8495-03e90e38f612.png',
  },
  {
    id: 17,
    title: '9th Grade - Internal Assessment',
    description: 'Iqra Educational Institute - High School internal assessment with excellent performance across all subjects including practical work and portfolio assessments',
    date: '2024-25',
    category: 'academic',
    likes: 22,
    image: '/lovable-uploads/1952e1ae-39cb-40b0-bae4-6536bbb98663.png',
  },
  {
    id: 18,
    title: '7th Grade - Academic Excellence',
    description: 'Iqra Educational Institute - Outstanding performance with 97.5% overall grade A1. Ranked 1st in class with excellent remarks from teachers',
    date: '2021-22',
    category: 'academic',
    likes: 30,
    image: '/lovable-uploads/8b03553c-4873-4f47-bb62-be210d485214.png',
  },
  {
    id: 19,
    title: '8th Grade - Sessional 5th Results',
    description: 'Iqra Educational Institute - Perfect performance in Sessional 5th examination with 100% marks and A+ grade. Position: 1st',
    date: '2023-24',
    category: 'academic',
    likes: 27,
    image: '/lovable-uploads/2193c1eb-ce8c-4177-b961-92dbac5f1c06.png',
  },
  {
    id: 20,
    title: '8th Grade - Sessional 6th Results',
    description: 'Iqra Educational Institute - Consistent excellence with 100% marks and A+ grade in Sessional 6th examination. Position: 1st',
    date: '2023-24',
    category: 'academic',
    likes: 26,
    image: '/lovable-uploads/d152ed72-6304-48ed-921e-1b59495280a0.png',
  },
  {
    id: 5,
    title: 'Dean\'s List Honor',
    description: 'Achieved Dean\'s List recognition for academic excellence with GPA above 3.8',
    date: '2023',
    category: 'academic',
    likes: 15,
  },
  {
    id: 6,
    title: 'Best Student Award',
    description: 'Recognized as the best student in Computer Science department',
    date: '2023',
    category: 'academic',
    likes: 22,
  },
  {
    id: 7,
    title: 'Merit Scholarship',
    description: 'Awarded full tuition scholarship based on academic performance',
    date: '2022-2024',
    category: 'scholarship',
    likes: 18,
  },
  {
    id: 8,
    title: 'Government Scholarship',
    description: 'Received state government scholarship for engineering students',
    date: '2022',
    category: 'scholarship',
    likes: 12,
  },
  {
    id: 9,
    title: 'React Developer Certificate',
    description: 'Completed advanced React development certification program',
    date: '2023',
    category: 'certificate',
    likes: 28,
  },
  {
    id: 10,
    title: 'Full Stack Development',
    description: 'Certified in full stack web development with MERN stack',
    date: '2023',
    category: 'certificate',
    likes: 31,
  },
  {
    id: 11,
    title: 'Final Year Results',
    description: 'Successfully completed final year with distinction (88%)',
    date: '2024',
    category: 'result',
    likes: 25,
  },
  {
    id: 12,
    title: 'Semester Topper',
    description: 'Topped the semester with highest marks in all subjects',
    date: '2023',
    category: 'result',
    likes: 19,
  },
  {
    id: 13,
    title: 'Tech Fest Winner',
    description: 'Won first prize in web development competition at college tech fest',
    date: '2023',
    category: 'event',
    likes: 34,
  },
  {
    id: 14,
    title: 'Hackathon Participant',
    description: 'Participated in 24-hour hackathon and developed innovative solution',
    date: '2023',
    category: 'event',
    likes: 16,
  },
];
